run:
  # timeout for analysis
  timeout: 10m

  go: "1.23"

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  whitespace:
    multi-func: true
    multi-if: true

linters:
  enable:
    - gofmt
    - whitespace
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - gocritic
    - godot
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    # TODO address issues with gosec and enable.
    # - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - typecheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - wastedassign
