{
 "title": "Channel Fees",
 "tags": [ "lightning-network" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Median Remote Fee Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, lnd_channels_remote_fee_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Remote Base Fee",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, lnd_channels_remote_base_fee_msat)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Local Fee Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, lnd_channels_local_fee_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Local Base Fee",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, lnd_channels_local_base_fee_msat)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Local Fees", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Base Fee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "targets": [
    {
     "expr": "lnd_channels_local_base_fee_msat",
     "legendFormat": "{{chan_id}}"
    }
   ]
  },
  {
   "title": "Fee PPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "lnd_channels_local_fee_rate", "legendFormat": "{{chan_id}}" }
   ]
  },
  { "title": "Remote Fees", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Base Fee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "targets": [
    {
     "expr": "lnd_channels_remote_base_fee_msat",
     "legendFormat": "{{chan_id}}"
    }
   ]
  },
  {
   "title": "Fee PPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "lnd_channels_remote_fee_rate", "legendFormat": "{{chan_id}}" }
   ]
  }
 ]
}