{
 "title": "Inbound Fees",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Negative Inbound Base Fee Values",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Base Fee [msat]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(lnd_graph_inbound_fee_base_msat_histogram_bucket{sign=\"negative\"}[30m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(lnd_graph_inbound_fee_base_msat_histogram_bucket{sign=\"negative\"}[30m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(lnd_graph_inbound_fee_base_msat_histogram_bucket{sign=\"negative\"}[30m])) by (le))",
     "legendFormat": "10th percentile"
    },
    {}
   ]
  },
  {
   "title": "Negative Inbound Fee Rate Values",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ppm", "label": "Fee Rate" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(lnd_graph_inbound_fee_rate_msat_histogram_bucket{sign=\"negative\"}[30m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(lnd_graph_inbound_fee_rate_msat_histogram_bucket{sign=\"negative\"}[30m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(lnd_graph_inbound_fee_rate_msat_histogram_bucket{sign=\"negative\"}[30m])) by (le))",
     "legendFormat": "10th percentile"
    },
    {}
   ]
  },
  {
   "title": "Adoption Negative Inbound Base Fee",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Number of Policies" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lnd_graph_inbound_fee_base_msat_histogram_bucket{le=\"+Inf\", sign=\"negative\"}[30m])",
     "legendFormat": "Policies"
    }
   ]
  },
  {
   "title": "Adoption Negative Inbound Fee Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Number of Policies" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lnd_graph_inbound_fee_rate_msat_histogram_bucket{le=\"+Inf\", sign=\"negative\"}[30m])",
     "legendFormat": "Policies"
    }
   ]
  },
  {
   "title": "Adoption Positive Inbound Base Fee",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "Number of Policies" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lnd_graph_inbound_fee_base_msat_histogram_bucket{le=\"+Inf\", sign=\"positive\"}[30m])",
     "legendFormat": "Policies"
    }
   ]
  },
  {
   "title": "Adoption Positive Inbound Fee Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "Number of Policies" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lnd_graph_inbound_fee_rate_msat_histogram_bucket{le=\"+Inf\", sign=\"positive\"}[30m])",
     "legendFormat": "Policies"
    }
   ]
  }
 ]
}