{
 "title": "Network Stats",
 "tags": [ "ligithning-network" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(lnd_chain_block_timestamp{namespace=\"$namespace\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Public Graph Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lnd_graph_nodes_count", "legendFormat": "num_graph_nodes" },
    { "expr": "lnd_graph_edges_count", "legendFormat": "num_graph_edges" }
   ]
  },
  {
   "title": "Total Channel Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "lnd_graph_chan_capacity_sat/1e8",
     "legendFormat": "total_chans_btc"
    },
    { "expr": "lnd_chain_block_height", "legendFormat": "lnd_chain_block_height" }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lnd_graph_nodes_count", "legendFormat": "num_nodes" }
   ]
  },
  {
   "title": "Channel Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "lnd_graph_edges_count", "legendFormat": "channel_count" },
    { "expr": "lnd_chain_block_height", "legendFormat": "lnd_chain_block_height" }
   ]
  },
  {
   "title": "Max HTLC ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "lnd_graph_max_htlc_msat_avg / 1000",
     "legendFormat": "max_htlc_avg"
    },
    {
     "expr": "lnd_graph_max_htlc_msat_median / 1000",
     "legendFormat": "max_htlc_median"
    }
   ]
  },
  {
   "title": "Min HTLC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lnd_graph_min_htlc_msat_avg / 1000",
     "legendFormat": "min_htlc_sat"
    },
    {
     "expr": "lnd_graph_min_htlc_msat_median / 1000",
     "legendFormat": "median_min_htlc"
    }
   ]
  },
  {
   "title": "CLTV Delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lnd_graph_timelock_delta_median",
     "legendFormat": "time_lock_delta_median"
    },
    { "expr": "lnd_graph_timelock_delta_avg", "legendFormat": "time_lock_delta_avg" }
   ]
  },
  {
   "title": "Node Out Degree",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lnd_graph_outdegree_max", "legendFormat": "max_out_degree" },
    { "expr": "lnd_graph_outdegree_avg", "legendFormat": "avg_out_degree" }
   ]
  },
  {
   "title": "Average Channel Fee Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(lnd_graph_fee_rate_msat_avg / 1000000) ",
     "legendFormat": "avg_fee_rate"
    },
    {
     "expr": "lnd_graph_fee_rate_msat_median / 1000000",
     "legendFormat": "median_fee_rate"
    }
   ]
  }
 ]
}