{
 "title": "Peer State",
 "tags": [ "ligithning-network" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(lnd_chain_block_timestamp{namespace=\"$namespace\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Num Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lnd_peer_count", "legendFormat": "num_peers" }
   ]
  },
  {
   "title": "Peer Flappiness (30s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "deriv(lnd_peer_count[40s])", "legendFormat": "peer_count_deriv" }
   ]
  },
  {
   "title": "Total Number of Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "irate(lnd_peer_sent_byte[5m])", "legendFormat": "{{ pubkey }}" }
   ]
  },
  {
   "title": "Total Number of Bytes Received ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "irate(lnd_peer_recv_byte[5m])", "legendFormat": "{{ pubkey }}" }
   ]
  },
  {
   "title": "Peer Ping Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "min((lnd_peer_ping_time_microsecond > 0) / 1000)",
     "legendFormat": "min_ping_ms "
    },
    {
     "expr": "max(lnd_peer_ping_time_microsecond / 1000)",
     "legendFormat": "max_ping_ms"
    },
    {
     "expr": "avg(lnd_peer_ping_time_microsecond / 1000)",
     "legendFormat": "avg_ping_ms"
    }
   ]
  },
  {
   "title": "Top 5 Outbound Bandwidth Hogs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "topk(5, lnd_peer_sent_byte)", "legendFormat": "{{ pubkey }}" }
   ]
  },
  {
   "title": "Top 5 Inbound Bandwidth Hogs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "topk(5, lnd_peer_recv_byte)", "legendFormat": "{{ pubkey }}" }
   ]
  },
  {
   "title": "Highest Sat Volume Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "topk(5, lnd_peer_sent_sat + lnd_peer_recv_sat > 0)",
     "legendFormat": "{{ pubkey }} "
    }
   ]
  }
 ]
}