{
 "title": "Watchtower",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful WT Backups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lnd_wt_client_num_backups[10m])",
     "legendFormat": "{{tower_pubkey}}"
    }
   ]
  },
  {
   "title": "Pending Backups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lnd_wt_client_num_pending_backups[10m])",
     "legendFormat": "{{tower_pubkey}}"
    }
   ]
  },
  {
   "title": "Session Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(lnd_wt_client_num_sessions[10m])",
     "legendFormat": "{{tower_pubkey}}"
    }
   ]
  }
 ]
}